POST http://localhost:3000/product-carbon-footprint HTTP/1.1
content-type: application/json

{
  "name": "product1",
  "ingredients": [
    { "name": "ham", "quantity": 0.2, "unit": "kg" },
    { "name": "cheese", "quantity": 0.3, "unit": "kg" },
    { "name": "tomato", "quantity": 0.25, "unit": "kg" }
  ]
}

###
GET http://localhost:3000/product-carbon-footprint HTTP/1.1
###
GET http://localhost:3000/product-carbon-footprint/3 HTTP/1.1
